### ISSUE TITLE
Airspeed sensor SDP31 not detected

### ISSUE THREAD

**Issue by Allerhopp** [mstrens/oXs_on_RP2040#64]
I've moved a working SDP31 sensor from Arduino to RP2040. It is not detected at bootup. Unfortunately no spare around. Did anybody get it to work?
[Monitor.zip](https://github.com/mstrens/oXs_on_RP2040/files/10955862/Monitor.zip)

**Comment by mstrens** [comment]
I have no sdp3x sensor.
So I could not test the code. I had to copy the code from oXs on AVR and to adapt it.
In order to help to find the bug could you try the version 1.7.2 I just put on github.
I added some debug message that should be displayed at power on,

Could you send me the messages generated just after a power on.
To get them, you must have the serial terminal active as soon as possible after power on.

Thanks

**Comment by Allerhopp** [comment]
Thanks!
I can try later additional pullup resistors. Maybe the i2c level is good enough for ms5611 but not for sdp? As a last resort I will revert back to Arduino to check the hardware.
[Monitor_2.zip](https://github.com/mstrens/oXs_on_RP2040/files/10957217/Monitor_2.zip)

**Comment by mstrens** [comment]
It is perhaps a bug in oXs.
Can you compile your self.
If so, you can try changing this line in sdp3x;cpp
There is
if ( i2c_read_timeout_us (i2c1 , _address , &readBuffer[0] , 9 , false, 1500) < 0)  {
   
You can try changing 1500 to 5000.
if ( i2c_read_timeout_us (i2c1 , _address , &readBuffer[0] , 9 , false, 5000) < 0)  {
    
If you can't compile yourself, just say it and I will put a version on github with the change.

**Comment by Allerhopp** [comment]
Thanks, but still no success:

19:44:00.325 -> trying to read sdpXX sensor with i2c adress = 21
19:44:00.325 -> error read first values from sdp3x
19:44:00.325 -> Setup1 takes 12851 usec
19:44:00.325 -> 
19:44:00.325 -> Version = 1.7.2

**Comment by mstrens** [comment]
It is strange.
I checked once more the code and do not see a bug.

It is strange because oXs can send the first command (a I2C write) but the next I2C code (a read) does not work.

Perhaps try adding pull up resistors (e.g. 4.7 k to 3.3V) on SCL and SDA

**Comment by Allerhopp** [comment]
The internal pullups from the parallel MS5611 are 2k (measured). Adding additionally 4.7 k and later 2.7 k pullups did not change the behaviour. MS5611 worked and SDP not. So I tried SDP alone with 4.7 k pullups but the result was still identical.

Connecting to Arduino M328 + MS5611 without additional pullups again proved the SDP is working. Difference between this two situations is only SDP VCC - which is 3.3 V vs. 4.8 V. But this should not matter according to the datasheet.

**Comment by mstrens** [comment]
That is strange.
Currently I try to read 9 bytes from sdp31 (after having send a command and waiting 20 msec)  just like for the pro mini version.

I just made a version 1.7.5 where I only read 1 bytes, then 2 bytes, ...9  (just to see if oXs can read it or not).
Could you try it and report the messages being generated

**Comment by Allerhopp** [comment]
Thanks! Here is the result:
15:25:41.829 -> trying to read sdpXX sensor with i2c adress = 21
15:25:41.829 -> read 1 byte from sdp3x = -2 
15:25:41.829 -> read 2 bytes from sdp3x = -2 
15:25:41.829 -> read 3 bytes from sdp3x = -2 
15:25:41.829 -> read 4 bytes from sdp3x = -2 
15:25:41.829 -> read 5 bytes from sdp3x = -2 
15:25:41.829 -> read 6 bytes from sdp3x = -2 
15:25:41.829 -> read 7 bytes from sdp3x = -2 
15:25:41.829 -> read 8 bytes from sdp3x = -2 
15:25:41.829 -> read 9 bytes from sdp3x = -2 
15:25:41.829 -> Setup1 takes 13709 usec
15:25:41.829 -> 
15:25:41.829 -> Version = 1.7.6

**Comment by mstrens** [comment]
The code -2 means a generic error on the I2C bus when reading the SDP3x.
This is strange because a write command sent by oXs just before did not generate the same error.
So the sensor is recognized (at least I expect).
I will look on internet if I can find some explanation.

**Comment by mstrens** [comment]
I read the datasheet of the sdp31 and I saw that it requires a special code at the end of each I2C command.
I add it in version 1.7.8 (on github).
I hope that now oXs can read the sensor.

**Comment by Allerhopp** [comment]
Thanks and sorry - still no data

18:33:01.735 -> trying to read sdpXX sensor with i2c adress = 21
18:33:01.735 -> read 9 bytes from sdp3x = -2 
18:33:01.735 -> Setup1 takes 12785 usec
18:33:01.735 -> 
18:33:01.735 -> Version = 1.7.9

**Comment by mstrens** [comment]
I do not understand.
Can you try new version 1.7.11
I inserted a first read before the first write , and a second write just to see if some of those commands are accepted.

**Comment by Allerhopp** [comment]
Sensor is detected!
20:02:48.474 -> trying to read sdpXX sensor with i2c adress = 21
20:02:48.474 -> read 3 bytes before the first write; return code  = -2 
20:02:48.568 -> read 9 bytes from sdp3x = 9 
20:02:48.568 -> sdp3x has been succesfuly detected
20:02:48.568 -> Setup1 takes 113336 usec
20:02:48.568 -> 
20:02:48.615 -> Version = 1.7.12 
and
20:02:48.615 -> Baro sensor is detected using MS5611
20:02:48.615 ->     Sensitivity min = 100 (at 100)   , max = 300 (at 1000)
20:02:48.615 ->     Hysteresis = 5 
20:02:48.615 -> Acc/Gyro is not detected
20:02:48.615 -> Airspeed sensor is detected using SDP3X

**Comment by mstrens** [comment]
It is probably because I increased a delay between the write and the read commands.
Datasheet says that 8msec is enough. I had 20 ms and I now put 100ms.

I made now a version 1.7.13 where I remove some code I added to debug.
I hope it continue to detect SDP31.
It could be that there are still some other bugs in the way airspeed / compensation is calculated. To be tested.

**Comment by Allerhopp** [comment]
All connected sensors are detected now!
The handset finds 2 VSpd, Alt and ASpd. One VSpd and Alt show changing numbers, the second VSpd (compensated ?) and ASpd stay at zero as you predicted.
Which communication channel do you prefer for further testing? Github Issue, RCG thread or Mail?
I close this issue since SDP is detected, thanks.

**Comment by mstrens** [comment]
The easiest for me is using the issues on github.
I get a mail each time there is a change so I do not have to look on the web site.
It is easier to archive and still to find back.
It is also easier for other user because it is sorted by topic.

Note: if AirSpeed is 0 on the the handset when it is positive with FV, then there is a bug somewhere.
Anyway, it does not seems normal having the second Vspeed always = 0.
Note: you can see the difference between the 2 Vspeed looking at the frsky field Id (normal Vspeed ends with 0 , compensated ends with F)
