### ISSUE TITLE
Fligt Test

### ISSUE THREAD

**Issue by Klippeneck** [mstrens/oXs_on_RP2040#66]
Hello mstrens,
over the weekend I was able to flight test the OXS Rp2040 sensor with MS5611 and GPS BN220. Function so far i. O., but the telemetry values of altitude, vario and GPS altitude are not correct. 
with another sensor. The values of the comparison sensor I have compared with a Jeti Vario 2, agree very well. The OXS baro height is about a factor of 1.25 too low.
At -10m altitude both sensors are the same and diverge again below -10m.(See log).
The GPS altitude oscillates between 81 and 98m. 
The climb values of the vario also differ strongly. Probably there is a bug in the altitude calculation.
Greetings Jürgen 

![Screenshot 2023-03-19 12 24 13](https://user-images.githubusercontent.com/64222996/226172498-74ae6c0b-a7fc-4c3d-af51-8680384bd278.png)

**Comment by mstrens** [comment]
For GPS, I saw the bug. The values from oXs where 10 X to small (I divided by 1000 instead of by 100 when I filled the data to be sent).
This is fixed in version 1.8.7.

I checked the formula to calculate baro altitude and I do not see immediately the bug.
Could you make a capture of the 3 altitudes with this new version.
With the right GPS altitude, it will be possible to have a better comparison. 
Could you also provide a graph of the 2 Vspeed (the one from oXs and the one from jeti vario) in the same flight.

**Comment by Klippeneck** [comment]
I can test GPS tomorrow with SW 1.87.
Vspeed from Jeti Vario and OXS I have attached.
![Screenshot 2023-03-19 12 25 47](https://user-images.githubusercontent.com/64222996/226177049-e29facb0-30f0-4703-a6ee-e6bbe2660c82.png)

**Comment by mstrens** [comment]
Based on the graph, Vspeed of oXs and Jeti seems me quite well correlated.
It seems that oXS provides higher value but this is not abnormal because I also note that it reacts faster.
So there is less damping.
It a choice I made.
It is possible to change the sensitivity of oXs (in config file) if you want.

**Comment by Klippeneck** [comment]
Hello mstrens,
attached are two logs, the first shows the takeoff, the second the whole flight.
The GPS altitude is shown as altitude above sea level, so I have adjusted the scaling in the diagram accordingly.
accordingly. In the altitude there are again differences between OXS and Jeti Vario. It is strange that at an altitude of -10m no deviations are to be seen.  

![Screenshot 2023-03-20 15 53 11](https://user-images.githubusercontent.com/64222996/226378479-603b69b6-e8ea-4ce9-8283-be3c45b57de6.png)
![Screenshot 2023-03-20 15 03 44](https://user-images.githubusercontent.com/64222996/226378516-a3437e9a-725f-4619-b3d7-3b21857360a3.png)

**Comment by Klippeneck** [comment]
And now with GPS altitude, OXS altitude and Jeti Vario altitude
![Screenshot 2023-03-20 16 02 52](https://user-images.githubusercontent.com/64222996/226381321-0fadafe7-fd11-4042-833c-8559a8be4765.png)

**Comment by Klippeneck** [comment]
Hello,
I already had the assumption, especially since the sensors are from China.
I will change the MS5611 and report again.
Thanks a lot .

**Comment by mstrens** [comment]
I presume this can be closed
