### ISSUE TITLE
Featurerequest: Transmit Cell Voltages from Graupner Voltage Sensor oder den FrSky MLVSS

### ISSUE THREAD

**Issue by Gernod** [mstrens/oXs_on_RP2040#76]
Is it possible to transfer the single cell voltages as supplied by the MLVSS sensor or Graupner Voltage Sensor? 

Thanks a lot
Gernod

**Comment by mstrens** [comment]
I would like to avoid this because:
- it will not work for most of the protocols
- it will require extra parameters to let oXs how to use the different voltages measurement (voltages based on Volt3, Volt4 and/or from ADS1115; one or several lipo, ...)
I think that when you use openTx or edgeTx, you can let the handset calculate himself the cell voltages the way you want.

**Comment by Gernod** [comment]
I can understand that. Then I will just configure the calculations in EdgeTX.

Thanks for the answer

Gernod
