### ISSUE TITLE
Consult SDP810-500PA for the reasons for unsuccessful airspeed testing

### ISSUE THREAD

**Issue by aepub** [mstrens/oXs_on_RP2040#93]
purchased an SDP810-500PA today, which uses a 5V voltage and is connected to the SDA and SCL of RP2040, including the previous MS5611 and MP6050. The SDA and SCL pins are connected to three sensors. Unfortunately, the remote control did not see the speed information, and I blew air into the airspeed tube, but there was no change.
![speed1](https://github.com/mstrens/oXs_on_RP2040/assets/44573941/51b3718f-a477-45c1-83af-bd5c9211961c)
![speed12](https://github.com/mstrens/oXs_on_RP2040/assets/44573941/82035ed6-c94a-409b-a48a-c1bc2c1a56e2)
![speed2](https://github.com/mstrens/oXs_on_RP2040/assets/44573941/d4125f3a-3c29-4080-ad03-f2a776232bcd)
![speed32](https://github.com/mstrens/oXs_on_RP2040/assets/44573941/13385b30-eea7-46a2-bd16-5c42b37cb6ad)
![speed244](https://github.com/mstrens/oXs_on_RP2040/assets/44573941/55096b6a-561f-4d6f-a2d2-b2587f795c71)

**Comment by mstrens** [comment]
It is strange that the SDP sensor is discovered (it means that it replies to his I2C address) but does not provide data.

I do not have such a sensor. So I wrote some code but I could not test it.
As far I remember some user tried a sdp3X successfully but I am not sure about the SDP810.

In the oXs program, there are 2 main parts:
- one get the data of the sensors and store the values internally
- the other one manages the communication with the receiver based on the selected protocol.

When the RP2040 is connected to a PC via the USB port, the PC can display some debug information and let you enter some commands (like you did when you selected the Exbus protocol).
There are 2 commands that can help finding in which part there is an error.
- if you enter the command "FV" (it means Field Values), the PC should display the internal values for all the installed sensors.
If you get a value other than 0 for the airspeed while applying a (de)pressure, it means that the first part of the code is ok. For this, it does not matter if oXs is connected to a receiver or not.
- if you enter a command "FVP" (it means Field Values Positive), oXs should transmit to the receiver all possible fields being foreseen in the selected protocol. The values being sent are just dummy values and are sent even for sensors that are not present. The goal is just to test the second part of the program.

Please make those tests.
If the bug is in the first part, I could make a version with even more debug messages in order to find the bug.

**Comment by mstrens** [comment]
Just to be sure: the sdp can measure differential pressures. It means that the returned pressure value can be positive or negative.
Only the positive values are used to calculate an airspeed (for negative values oXs return 0).
Are you sure that you connected the sensor in the right way to the pitot tubes?

**Comment by mstrens** [comment]
When you send the FVP command, did you get an airspeed value (other than 0) on the handset?

Without sending a command, did you try to invert your 2 tubes connecting the pitot and the sensor.

**Comment by mstrens** [comment]
So the FVP values are transmitted. So the bug should be in the first part of the code.

Here a version 2.7.1 (not available on github) to check if oXs can read the data from the SDP.
Use it with the RP2040 connected to the PC (via USB).
Every 2 msec, oXs is supposed to read the SDP and if OK, it should (with this version) send to the PC a line with 3 values about the pressure (raw values);
Could you make a copy/paste of some of those lines when blowing in the pitot tube to see what oXs get from the sensor.

[oXs.zip](https://github.com/mstrens/oXs_on_RP2040/files/12327566/oXs.zip)

**Comment by mstrens** [comment]
No, I forgot it.
I will make a new version.

**Comment by mstrens** [comment]
Here with I2S = 0X25
[oXs.zip](https://github.com/mstrens/oXs_on_RP2040/files/12327726/oXs.zip)

**Comment by mstrens** [comment]
It is strange!
oXs does not get an error when reading the sensor but the values are always 0 (on first 2 bytes)

Here a version (2.7.2) 
[oXs.zip](https://github.com/mstrens/oXs_on_RP2040/files/12327783/oXs.zip)
where I should read the 9 bytes provided by the sensor (pressure, temp, scale and crc).
I removed the previous message and I inserted only one line of message with the data captured when the sensor is initialized.
The line begins with  "SDP first read:" and should contains 9 values.

**Comment by mstrens** [comment]
Perhaps I found the bug.
Here a version 2.7.3 with
- same message expected as version 2.7.2
- a fix in the way I write/read with the sensor.
[oXs.zip](https://github.com/mstrens/oXs_on_RP2040/files/12327798/oXs.zip)

**Comment by mstrens** [comment]
I presume that using 4.7K pull-up to 3.3V is ok.
In theory using also a MS5611 and MP6050 should not be an issue. Still I saw a post on Rcgroups about a GY86 module that delivers no altitude. So I am not 100% sure.

With version 2.7.2 (or 2.7.3), oXs should, after a reset, generate a line starting with "SDP first read:" followed by 9 values.
Do you get such a line? If yes, what are the 9 values?
Note: it is just generated once (after each reset) during the setup of oXs.

If you can easily disconnect the MS5611+MP6050 from the I2C bus, you could also make a test without those components.
If it is difficult to disconnect them, I could make a version of oXs where I do not try to read those addresses.

**Comment by mstrens** [comment]
I just noticed that when you did not yet used a FVP of FVN command, the compensated VSpeed displayed on the handset seems abnormal (to high value).
If you did not yet disconnected the MS5611, could you also display the uncompensated value of Vspeed (this one is calculated based only the MS5611) and should be close to 0 when the sensor does not move up/down.

**Comment by mstrens** [comment]
It is clear that when oXs tries to get data from the SDP, it get only 0.
I do not understand why.
There are no real errors detected on the I2C bus. When oXs sent commands, it checks that the I2C sensor replies with an ACK. That seems to be the case. This works because when we use a wrong I2C address, we get an error.

I can make change to oXs to see if I can read e.g. the type of SDP. This require specific commands I think.
I will check the datasheet.
 
It would also be possible to test just the SDP alone if you could be able to connect it to another MCU board (e.g. an RP2040 zero or an arduino uno/pro mini/nano). Do you have such a board?

**Comment by mstrens** [comment]
Here a comment for a previous test you made:
FV just after a clean boot (so before a FVP or FVN) gives the values that oXS get (calculates) from the sensors.
Vspeed seems OK. So MS5611 is OK
Airspeed has a very high value but this is the result of getting 0 in reply from the SDP during the initilization process.

At this stage, FVP and FVN commands does not help because the issue is not  in the second part of the program (when data are transmitted)

About you test with a RP2040 zero alone: It seems it is the same issue.

I made a new 2.7.4 version (in attachement) where oXs tries to read the product identifier of the SDP.
Just like previous version, there should be a one line message that begin with "SDP product first bytes:" generated during the initialization after each reboot.
This lines should contains also 9 values. At least some should be different from 0.
[oXs.zip](https://github.com/mstrens/oXs_on_RP2040/files/12329229/oXs.zip)

**Comment by mstrens** [comment]
at least with this test, the 9 values are not all 0.
Still I suspect that those are not the expected values (does not seems to be the product ID given in the datasheet).
So it could be that this is just the content of an un-intialized buffer.
To clarify this, I made a version 2.7.5 where I prefill the buffer with special values before reading the SDP.
Can you try this version and report the same lines as before
[oXs.zip](https://github.com/mstrens/oXs_on_RP2040/files/12329399/oXs.zip)

**Comment by mstrens** [comment]
Thanks for testing.
The values are the same as in previous tests.
I presume they are really returned by the sensor because in 2.7.5 oXs pre-fill the buffer with other values.  
The returned values are very strange.
19:21:15.869 -> SDP product first bytes: 0 0 81 2 F0 DA 0 0 0
19:21:15.947 -> SDP first read: 0 0 81 2 F0 DA 0 0 0
3rd value = "81" should be a CRC on the first 2 (= 0 0).
9th value = "0" should be a CRC on the 7 and 8 values (= 0 0).
I did not yet checked how CRC is calculated but in any case, it is not normal having 2 different CRC (once 81 and once 0) for the same values (0 0).

At this stage, I do not understand.
I will have to stop testing for today because I have to leave home.
I will further think on the issue.
We can continue to morrow if it is ok for you.
Do you have an arduino board (uno, pro mini, nano) that could be used for testing a total different program just for SDP?

**Comment by mstrens** [comment]
I checked CRC calculation.
When we get 0 0 81 2 F0 DA 0 0 0, I noticed that:
81 is indeed the CRC of 0 0
DA is indeed the CRC of 2 F0
The last 0 is strange because it is not the CRC of the 0 0 before.
I do not understand. It looks like the sensor  reply only part of the expected data.

Furthermore, it is strange that the sensor provided the same reply when oXs requested the product ID and when oXs requested the pressure/temperature.

I made a version 2.7.6 where oXs 
- first sent a STOP command (to stop a continuous conversion mode
- then read 9 bytes from SDP (just to se
[oXs.zip](https://github.com/mstrens/oXs_on_RP2040/files/12332978/oXs.zip)
e)
- then sent a RESET command
- then ask for the product ID.
- then read the full reply (18 bytes) 
- then ask for continuous conversion
- and finally read  a conversion (9 bytes)

**Comment by mstrens** [comment]
If version 2.7.6 does not help, I suggest to make a test with another program.
I found some arduino program made by sensirion (manufacturer of sdp8xx).
Here is a link to this program
https://github.com/Sensirion/arduino-i2c-sdp

The instructions are given in the link (in the readme section.
Please note that you have first to install this program as a library.
Then there is a second library to install (see the link under Dependancies" in the readme section).
In Arduino IDE, I installed the package  for the board RP2040. In menu "tools" + "board manager", there a several options for RP2040. I selected the package made by philhower. This package allows to select a board Waveshave RP2040-Zero.
Once the board and the libraries are installed, it is possible to use the example provided by Sensirion (with menu "Files"+ "Example" + "Sesirion I2C SDP" +  "ExempleUsage"
I could not test it myself but I could at least compile it.
Note: I do not know at this stage which GPIO pins are used for the I2C with this program. I suspect they are not the same as oXs. I can eventually look for this.

The program is supposed to display the product ID of your device and then the pressure and temperature.
If it works, then the issue is in oXs and it makes sense to continue to search for a solution.
If it does not work with this original sensirion program, then I presume your device is defect.

**Comment by mstrens** [comment]
This probably explains that oXs did not work.
I just had a look at the ADP810 datasheet and even if it looks quite similar, it does not support all commands as SDP810.

If you want, it is probably possible to change oXs code in order to use ADP810 but performance will be less than with SDP810.
It  requires about 10ms minimum per pressure conversion while SDP requires only 500ms, calculates itself averages and does not require a new I2C command for each conversion. So ADP810 will probably give more noisy measurement but perhaps this is still acceptable.

Let me know if you want that I adapt oXs code to support ADP810.

**Comment by mstrens** [comment]
I made some changes in order to use an ADP810 (I hope).
After a reboot, oXs should display a line beginning with "SDP first read" and 9 values. Those values should be different from all 0 or a sequence 0 1 2 3... 
You can test it with you standalone RP2040.
You can also (with this stand alone device) send several FV commands (not FVP nor FVN). Airspeed should be present in the displayed values on pc with a value different from 0 if you blow on the pitot tube  

If this works, you should get airspeed on the handset with you other rp2040

Here version 2.7.7
[oXs.zip](https://github.com/mstrens/oXs_on_RP2040/files/12342752/oXs.zip)

**Comment by mstrens** [comment]
It is strange that version 2.7.1 does not detect the SDP810.
Are you sure that I2C address was changed to 0X25?
I presume you tested this version with a board having GPS MS5611 and MP6050.

About version 2.7.8: this version has been compiled with a parameter defined for an ADP 810.
I should have to compile it again to make a version for SDP810. 
Still, I had expected that it should work with an SDP because the ADP commands are also supported by the SDP.
Furthermore it seems that the first commands sent during the setup are accepted because the 9 values reported on the PC seems just OK (e.g. pressure is nearly 0 and temperature is about 30°C). In the main loop oXs uses the same command and those are rejected. Very strange.
Furthermore, at the beginning there are  messages about errors with MS5611 and MPU6050 and after some messages those errors disappear.

It looks like something goes wrong with I2C bus.
Do you use long wires for I2C?
Perhaps can you also try to reduce the value of the pullup resistors (e.g. 2.2K instead of 4.7).

**Comment by mstrens** [comment]
Here a version 2.7.10 for SDP810 (and with some changes about I2C for MPU6050). 
Hoping it helps.
[oXs.zip](https://github.com/mstrens/oXs_on_RP2040/files/12372974/oXs.zip)

**Comment by mstrens** [comment]
The changes I made to support ADP810 require some changes in the config.h file.
So changing the type of sensor requires to edit the config.h file and to recompile/reflash. 
Version 2.7.11 has been made for SDP810.
I can compile another version if you want for ADP810. Still I am not sure it makes really sense to keep this option in official oXs because I presume that the SDP810 let you get more much reliable data. As both sensors cost about the same, I would recommend to use only SDP810.
But it is not an issue to make a compilation once for you in order to let you use your ADP810.
Just let me know if you want it or not.
